# Generated by Django 3.0.5 on 2020-05-08 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='Body',
            field=models.TextField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='article',
            name='EDate',
            field=models.DateField(default='1111-11-11'),
        ),
        migrations.AlterField(
            model_name='article',
            name='Location',
            field=models.CharField(choices=[('贵州', '贵州'), ('陕西', '陕西'), ('江西', '江西'), ('新疆', '新疆'), ('天津市', '天津市'), ('重庆市', '重庆市'), ('吉林', '吉林'), ('广东', '广东'), ('海南', '海南'), ('黑龙江', '黑龙江'), ('北京', '北京'), ('台湾', '台湾'), ('浙江', '浙江'), ('湖北', '湖北'), ('甘肃', '甘肃'), ('西藏自治区', '西藏自治区'), ('内蒙古自治区', '内蒙古自治区'), ('广西壮族自治区', '广西壮族自治区'), ('宁夏回族自治区', '宁夏回族自治区'), ('福建', '福建'), ('河北', '河北'), ('江苏', '江苏'), ('四川', '四川'), ('山东', '山东'), ('辽宁', '辽宁'), ('青海', '青海'), ('上海市', '上海市'), ('澳门特别行政区', '澳门特别行政区'), ('山西', '山西'), ('河南', '河南'), ('云南', '云南'), ('香港特别行政区', '香港特别行政区'), ('湖南', '湖南'), ('安徽', '安徽')], max_length=50),
        ),
        migrations.AlterField(
            model_name='article',
            name='Public',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='SDate',
            field=models.DateField(default='1111-11-11'),
        ),
        migrations.AlterField(
            model_name='article',
            name='Title',
            field=models.CharField(max_length=40),
        ),
    ]
