# Generated by Django 3.0.5 on 2020-05-09 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a', '0003_auto_20200509_1645'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['SDate']},
        ),
        migrations.AlterField(
            model_name='article',
            name='Location',
            field=models.CharField(choices=[('河北', '河北'), ('台湾', '台湾'), ('湖南', '湖南'), ('江西', '江西'), ('湖北', '湖北'), ('海南', '海南'), ('黑龙江', '黑龙江'), ('天津市', '天津市'), ('山西', '山西'), ('贵州', '贵州'), ('澳门特别行政区', '澳门特别行政区'), ('青海', '青海'), ('甘肃', '甘肃'), ('上海市', '上海市'), ('辽宁', '辽宁'), ('内蒙古自治区', '内蒙古自治区'), ('广西壮族自治区', '广西壮族自治区'), ('安徽', '安徽'), ('西藏自治区', '西藏自治区'), ('吉林', '吉林'), ('福建', '福建'), ('江苏', '江苏'), ('浙江', '浙江'), ('广东', '广东'), ('四川', '四川'), ('陕西', '陕西'), ('新疆', '新疆'), ('北京', '北京'), ('宁夏回族自治区', '宁夏回族自治区'), ('河南', '河南'), ('香港特别行政区', '香港特别行政区'), ('山东', '山东'), ('重庆市', '重庆市'), ('云南', '云南')], max_length=50),
        ),
    ]
